### ISSUE TITLE
provide autoloads

### ISSUE THREAD

**Issue by NobbZ** [anildigital/mix-format.el#10]

**Comment by anildigital** [comment]
Thanks! @ckruse any idea how to implement this?

**Comment by NobbZ** [comment]
Autoloading is described in the maunal: https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html

When your package gets installed by `package.el`, then autoloads will be generated automatically for all all functions that are preceeded with the line `;;;###autoload`.

eg:

```el
;;;###autoload
(defun foo ()
  '())
```

Since I am managing my packages via Cask, which installs via package.el even for non-ELPA packages, for me the annotated functions were enough.

**Comment by ckruse** [comment]
Yes. Will have a look at it as soon as I have the time (probably this evening).

**Comment by ckruse** [comment]
created a pull request; was less work than I thought, as @NobbZ said: adding annotations was enough
