### ISSUE TITLE
Calling `mix format` on the file itself

### ISSUE THREAD

**Issue by ckruse** [anildigital/mix-format.el#4]
Hey,

what do you think about calling `mix format` on the file itself? Currently `mix-format.el` pipes the contents of the file to `stdin` of `mix format`; this has the advantage that one can format a buffer without saving it. But it has a big disadvantage: `.format.exs` gets ignored.

What's your opinion?

Regards,
 CK

**Comment by anildigital** [comment]
@ckruse I think we should make it customizable. The default behaviour can be as it is now. To support .format.exs, one can customize the option.
