### ISSUE TITLE
Warnings are getting added in the source file after save.

### ISSUE THREAD

**Issue by anildigital** [anildigital/mix-format.el#5]
<img width="502" alt="screenshot 2017-11-02 13 51 06" src="https://user-images.githubusercontent.com/266/32316123-e52c72e4-bfd4-11e7-9255-2c2541fb8b12.png">

@ckruse this might be related to #4

**Comment by ckruse** [comment]
I can't reproduce that, to be honest… can you retry with latest elixir HEAD?

**Comment by anildigital** [comment]
@ckruse Here are Elixir version details

```
]$ elixir --version
Erlang/OTP 20 [erts-9.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.0-dev (385115f) (compiled with OTP 20)
```

and here is the gist of the source file where warnings are getting added as shown. https://gist.github.com/anildigital/ad278e87344841c8757a8f64204ec880

**Comment by ckruse** [comment]
Thanks, I was able to reproduce the problem. I created a pull request fixing this issue.

**Comment by anildigital** [comment]
Thanks!
